import type { Metadata } from "next"; // Ensure Metadata type exists in the 'next' package
import { Inter } from "next/font/google"; // Check for correct font name and package installation
import "./globals.css"; // Verify the file path
import Header from "@/components/Header"
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
